title: Legibility
title_en: Legibility
title_es: Legibilidad
author: Mary C. Dyson
keywords: legibility, reading, typography, book, research
# email: info@legible-typography.com
description: >- # this means to ignore newlines until "baseurl:"
  Understanding the important role of typography in reading is a key subject that designers should know and learn about. Design for reading is an enormous responsibility that we should face and resolve correctly.
  In these pages you will find an explanation of how one reads, the movement of our eyes when we read, how we recognize words. You will find excellent material of a diverse nature and complexity that will help understand the basic princi- ples of typography, wrong ideas and practices that are common in the profession, and advanced concepts of reading on the screen supported by scientific research.
  The mastery detail of how to regard type is fully developed by Mary C. Dyson who has devoted her academic life to searching for answers and convey designers of her findings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://legible-typography.com" # the base hostname & protocol for your site, e.g. http://example.com
email: info@rosettatype.com
last_update: 2. May 2023
last_book_compile: 2023-05-04

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  sass_dir: assets/css

collections:
  chapters_en:
    output: true
    # Output the chapters as root URLs
    permalink: en/:name

  glossary_en:
    output: true
    permalink: en/glossary#:name

  # Spanish version  
  chapters_es:
    output: true
    # Output the chapters as root URLs
    permalink: es/:name

  glossary_es:
    output: true
    permalink: es/glossary#:name

# Set default page.lang attributes for chapters and pages based on scopes
defaults:
  -
    scope:
      path: ""
      type: "chapters_en"
    values:
      lang: "en"
      layout: "chapter"
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: "page"
  -
    scope:
      path: ""
      type: "chapters_es"
    values:
      lang: "es"
      layout: "chapter"

