# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Legibility
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Understanding the important role of typography in reading is a key subject that designers should know and learn about. Design for reading is an enormous responsibility that we should face and resolve correctly.
  In these pages you will find an explanation of how one reads, the movement of our eyes when we read, how we recognize words. You will find excellent material of a diverse nature and complexity that will help understand the basic princi- ples of typography, wrong ideas and practices that are common in the profession, and advanced concepts of reading on the screen supported by scientific research.
  The mastery detail of how to regard type is fully developed by Mary C. Dyson who has devoted her academic life to searching for answers and convey designers of her findings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .vscode/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  sass_dir: assets/css

collections:
  chapters:
    output: true
    # Output the chapters as root URLs
    permalink: /:name

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "post"
